/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("java")
    kotlin("jvm") version "2.0.0-Beta3" apply true
}

java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17

group = "io.github.toomanylimits"
version = "0.1.0"
description = "Snuggle"

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
    gradlePluginPortal()
}

//https://discuss.gradle.org/t/how-to-include-dependencies-in-jar/19571/4
val extraLibs by configurations.creating

dependencies {
    //https://discuss.gradle.org/t/how-to-include-dependencies-in-jar/19571/4
//    api("org.jetbrains.kotlin:kotlin-stdlib:1.8.10")
    extraLibs("org.jetbrains.kotlin:kotlin-stdlib:1.8.10")
    api("org.ow2.asm:asm:9.6")
    api("org.ow2.asm:asm-util:9.4")
    api("org.ow2.asm:asm-tree:9.4")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:1.8.10")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.0")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

//https://discuss.gradle.org/t/how-to-include-dependencies-in-jar/19571/4
tasks.jar {
    from(extraLibs.map { if (it.isDirectory) it else zipTree(it) })
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
